### PR TITLE
Adding of support for vouchers

### PR DESCRIPTION
**Pull request by BlackSmith**

### CODE REVIEW

**Comment by finish06** [comment]
@BlackSmith Thank you for the pull request!  Life is busy at the moment with school starting, however I will attempt to merge in the coming 7 days.

**Comment by BlackSmith** [comment]
You are welcome. :) 
Can I ask you, I want to use unifi vouchers on my external authentication portal. I found out that the Unifi controller API does not support guest authentication via voucher. I can get all vouchers and check it in my script, after that I can use authorize_guest and enable of guest.
Unfortunately in this case, the voucher is still unused and expiration time does not start counting. Voucher never expire. :(

Do you have any idea how to solve this problem?
Thank you in advance.

**Comment by finish06** [comment]
Could you script run the `delete_voucher` method after a period of time?

**Comment by finish06** [comment]
Further, the README contribution is great!  I definitely think a solid API library needs good documentation so thank you.  I do not use voucher functionality in my build, nor know much about it.  Therefore, I am going to have faith the functionality works as the code looks good.

**Pull request merged**
