### PR TITLE
Add new method to update user group bandwidth.

### PR DESCRIPTION
**Pull request by rbdixon**
Also implements _api_update() method to all PUT calls.

Let me know if you would rather not check the user group ID prior to sending the PUT request. I'm good with it either way.

### CODE REVIEW

**Comment by finish06** [comment]
Are you interested in resolving the conflicts due to recent pull request?

**Comment by rbdixon** [comment]
There you go. Sorry about the delay.

**Comment by rbdixon** [comment]
The two build failures above are due to deficiencies in the `requirements.txt` file. I didn't introduce any new dependencies so won't address those build failures in this PR.

**Comment by finish06** [comment]
Looks good.  Thank you for the contribution!

**Pull request merged**
