### PR TITLE
Add some more functionalities

### PR DESCRIPTION
**Pull request by The-Loeki**
* upgrade_firmware
* get_setting
* update_setting
* force provisioning
* switch_site -> switch api to another site

### CODE REVIEW

**Comment by finish06** [comment]
@The-Loeki - Thank you for the contribution.  I am out of town for the next week and will plan to review once back at the homestead.

**Comment by The-Loeki** [comment]
np, there might be even more in the meantime so no worries ;)

**Comment by finish06** [comment]
Looks great @The-Loeki.  Thank you for the contribution.

**Comment by finish06** [comment]
FYI -> repackaged for pypi.  Version = 2.14

**Pull request merged**
